### ISSUE TITLE
Fix paths to match legacy URLs

### ISSUE THREAD

**Issue by glaslos** [honeynet/honeynet.github.io#23]
We currently use the standard routing based on menu item + content folder. This is not matching what we used to have.

See https://gohugo.io/content-management/urls/#url on how to modify 

Legacy:
`honeynet.org/2022/10/06/gsoc-2022-project-summary-creating-playbooks-for-intelowl/`

Current Hugo:
`honeynet.org/blog/2022-10-06-gsoc-2022-project-summary-creating-playbooks-for-intelowl/`

What needs to be done:
- Move all blog posts into a yyyy/mm/dd folder structure
- Removed the blog/ prefix from the path

Try this:
```yaml
# Remove the "/posts/", "/categories/", "/tags/" prefixes from URLs.
permalinks:
    posts: '/:filename/'
    categories: '/:slug/'
    tags: '/:slug/'
```
